[package]
name = "muservc"
version = "0.1.0"
authors = ["Gaoyuan Du -- zzr123 <2296704779@qq.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
[profile.release]
debug = true
#![feature(c_variadic)]